insert into BLOGGERS (name,email,registration_date) values ('Gyula','gyula@pipike.com',CURRENT_TIMESTAMP())
insert into BLOGGERS (name,email,registration_date) values ('Ubulka','ubi@savanyu.com',CURRENT_TIMESTAMP())
insert into STORIES (title,content,latest_updated,blogger_id) values ('Első teszt','Teszt tartalom',CURRENT_TIMESTAMP(),(select id from BLOGGERS where name='Gyula'))
insert into STORIES (title,content,latest_updated,blogger_id) values ('Második teszt','Elmentünk ma epret szedni egy szedd-magad akcióban.',CURRENT_TIMESTAMP(),(select id from BLOGGERS where name='Gyula'))
insert into STORIES (title,content,latest_updated,blogger_id) values ('Az én sztorim','Figyeljetek, nagyon érdekes sztorim van!',CURRENT_TIMESTAMP(),(select id from BLOGGERS where name='Ubulka'))
insert into STORIES (title,content,latest_updated,blogger_id) values ('Második sztorim','Folytatom a tegnapi gondolatmenetemet.',CURRENT_TIMESTAMP(),(select id from BLOGGERS where name='Ubulka'))